### PR TITLE
Add rules for v1.2.0

### LINKED ISSUE #13: Reconsider `lines_longer_than_80_chars`
I would like to discuss and maybe reconsider adding the [`lines_longer_than_80_chars`](https://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html) lint rule.

This package should aim to follow the Effective Dart guide **as much as possible** and disabling this lint rule is probably *opinionated*. Given the fact that you can easily [suppress](https://github.com/tenhobi/effective_dart#suppressing-lints) any lint rule per project, file or line, I would like to reconsider this and add it to the lints we use.

Cc @felangel as you have for now the biggest projects using this package.

### LINKED ISSUE #14: Add implementation_imports
After approval of https://github.com/dart-lang/site-www/pull/2187, add `implementation_imports`.

### LINKED ISSUE #15: Add prefer_relative_imports
After approval of https://github.com/dart-lang/site-www/pull/2188, add `prefer_relative_imports`.

### LINKED ISSUE #16: Add camel_case_extensions
After approval of https://github.com/dart-lang/site-www/pull/2186, add `camel_case_extensions`.

### LINKED ISSUE #17: Add avoid_catching_errors
After approval of https://github.com/dart-lang/site-www/pull/2190, add `avoid_catching_errors`.

### LINKED ISSUE #18: Add prefer_mixin
After approval of https://github.com/dart-lang/site-www/pull/2191, add `prefer_mixin`.

### LINKED ISSUE #19: Add avoid_types_on_closure_parameters
After approval of https://github.com/dart-lang/site-www/pull/2192, add `avoid_types_on_closure_parameters`.

### LINKED ISSUE #20: Add avoid_equals_and_hash_code_on_mutable_classes
After approval of https://github.com/dart-lang/site-www/pull/2193, add `avoid_equals_and_hash_code_on_mutable_classes`.

### PR DESCRIPTION
**Pull request by tenhobi**
After going throgh Effective Dart guide, I have proposed adding a few (in my opinion) missed rules reference. I am awaiting adding them to the guide. 

Changes:

- Add [`lines_longer_than_80_chars`](https://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html)
- Add [`implementation_imports`](https://dart-lang.github.io/linter/lints/implementation_imports.html)
- Add [`prefer_relative_imports`](https://dart-lang.github.io/linter/lints/prefer_relative_imports.html)
- Add [`camel_case_extensions`](https://dart-lang.github.io/linter/lints/camel_case_extensions.html)
- Add [`avoid_catching_errors`](https://dart-lang.github.io/linter/lints/avoid_catching_errors.html)
- Add [`prefer_mixin`](https://dart-lang.github.io/linter/lints/prefer_mixin.html)
- Add [`avoid_types_on_closure_parameters`](https://dart-lang.github.io/linter/lints/avoid_types_on_closure_parameters.html)
- Add [`avoid_equals_and_hash_code_on_mutable_classes`](https://dart-lang.github.io/linter/lints/avoid_equals_and_hash_code_on_mutable_classes.html)

Fixes #13 
Fixes #14  
Fixes #15 
Fixes #16 
Fixes #17 
Fixes #18 
Fixes #19 
Fixes #20

### CODE REVIEW

**Comment by tenhobi** [comment]
Every dependency approved, I will merge in the evening.

**Comment by tenhobi** [comment]
@pq could you, please, update lints page, so it would reflect updates? 💙

**Comment by pq** [comment]
Do you mean links from the individual rule docs?

Like:

https://github.com/dart-lang/linter/blob/master/lib/src/rules/camel_case_types.dart#L15

**Comment by tenhobi** [comment]
Hmm, more like regenerating this page http://dart-lang.github.io/linter/lints/, so badges for newly added lints would show up. :-)

**Comment by pq** [comment]
Ah!  That's easier.  I can do that quickly.

Having said that, I do think all the rules should have back-pointers inlined in the docs for discoverability and consistency.

For example, I see `lines_longer_than_80_chars` does not.

**Comment by pq** [comment]
> regenerating this page

done. 👍 

image

(etc)

**Comment by tenhobi** [comment]
Awesome 💙

**Pull request merged**
